name: dotnetcore-webapp-ci-cd

on:
  push:
    branches:
      #- feature/*
      - release/*
      - develop
  pull_request:
    branches:
      - develop
      - main

permissions:
  pull-requests: write
  contents: write
  statuses: write
  checks: write
  actions: write    
  security-events: write
  
env:
  CONFIGURATION: Release
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: Show variables
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_SHA: $GITHUB_SHA"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"
        echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
        echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "GITHUB_ACTION: $GITHUB_ACTION"
        echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
        echo "RUNNER_OS: $RUNNER_OS"
        echo "RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
        echo "RUNNER_TEMP: $RUNNER_TEMP"
        echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
        echo "ACTIONS_RUNTIME_URL: $ACTIONS_RUNTIME_URL"

    - name: Setup dotnet version
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/MyFirstProject.sln
    
    - name: Build
      run: dotnet build src/MyFirstProject.sln --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test src/MyFirstProject.Tests/MyFirstProject.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --verbosity normal --logger "junit;LogFilePath=TestResults/tests.xml"
    
    - name: Display Folder
      run: ls -R

    #- name: Create test summary
    #  uses: test-summary/action@dist
    #  with:
    #    paths: src/MyFirstProject.Tests/TestResults/tests.xml
    #  if: success() || failure()

    #- name: Test Report
    #  uses: dorny/test-reporter@v1
    #  if: success() || failure()
    #  with:
    #    name: UnitTests
    #    path: src/MyFirstProject.Tests/TestResults/tests.xml
    #    reporter: java-junit
    
    #- name: Dependency Review
    #  uses: actions/dependency-review-action@v4
    #  if: ${{ github.event_name == 'pull_request' }}
    #  with:
    #    comment-summary-in-pr: always
          
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp
        #queries: security-extended,security-and-quality
        queries: security-extended
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:csharp"
    
    - name: Publish APP
      run: dotnet publish src/MyFirstProject.WebApp/MyFirstProject.WebApp.csproj --no-build --configuration ${{ env.CONFIGURATION }} --output PublishApp

    - name: Publish API
      run: dotnet publish src/MyFirstProject.WebApi/MyFirstProject.WebApi.csproj --no-build --configuration ${{ env.CONFIGURATION }} --output PublishApi
    
    - name: Upload APP Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-artifact
        path: PublishApp
    
    - name: Upload API Artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-artifact
        path: PublishApi

  Dev:
    needs: 
      - Build
    runs-on: ubuntu-latest
    environment:
      name: webapp-dev
      url: https://app-dotnetproject-dev.azurewebsites.net
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/download-artifact@v4
      
      - name: Set version date
        run: |
          echo "APP_VERSION_DATE=$(date +'%d/%m/%Y %H:%M:%S')" >> $GITHUB_ENV
          
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: rg-dotnetproject-dev
          app-name: api-dotnetproject-dev
          package: api-artifact
        
      - name: Set APP Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: app-dotnetproject-dev
          app-settings-json: |
            [
              {
                "name": "VersionInfo__Number",
                "value": "1.0.${{ github.run_number }}",
                "slotSetting": false
              },
              {
                "name": "VersionInfo__Date",
                "value": "${{ env.APP_VERSION_DATE }}",
                "slotSetting": false
              }
            ]

      - name: Deploy APP
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: rg-dotnetproject-dev
          app-name: app-dotnetproject-dev
          package: app-artifact
  
  Hml:
    needs: 
      - Build
    runs-on: ubuntu-latest
    environment: webapp-hml
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    steps:
      - uses: actions/download-artifact@v4
      
      - name: Set version date
        run: |
          echo "APP_VERSION_DATE=$(date +'%d/%m/%Y %H:%M:%S')" >> $GITHUB_ENV
          
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: rg-dotnetproject-hml
          app-name: api-dotnetproject-hml
          package: api-artifact
        
      - name: Set APP Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: app-dotnetproject-hml
          app-settings-json: |
            [
              {
                "name": "VersionInfo__Number",
                "value": "1.0.${{ github.run_number }}",
                "slotSetting": false
              },
              {
                "name": "VersionInfo__Date",
                "value": "${{ env.APP_VERSION_DATE }}",
                "slotSetting": false
              }
            ]

      - name: Deploy APP
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: rg-dotnetproject-hml
          app-name: app-dotnetproject-hml
          package: app-artifact

  Prd:
    needs: 
      - Hml
    runs-on: ubuntu-latest
    environment: webapp-prd
    steps:
      - uses: actions/download-artifact@v4
      
      - name: Set version date
        run: |
          echo "APP_VERSION_DATE=$(date +'%d/%m/%Y %H:%M:%S')" >> $GITHUB_ENV
          
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: rg-dotnetproject-prd
          app-name: api-dotnetproject-prd
          package: api-artifact
        
      - name: Set APP Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: app-dotnetproject-prd
          app-settings-json: |
            [
              {
                "name": "VersionInfo__Number",
                "value": "1.0.${{ github.run_number }}",
                "slotSetting": false
              },
              {
                "name": "VersionInfo__Date",
                "value": "${{ env.APP_VERSION_DATE }}",
                "slotSetting": false
              }
            ]

      - name: Deploy APP
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: rg-dotnetproject-prd
          app-name: app-dotnetproject-prd
          package: app-artifact
