name: dotnetcore-webapp-ci

on:
  #push:
  #  branches: 
  #    - main
  #    - feature/*
  #  paths-ignore:
  #    - 'docs/**'
  #    - '.github/**'
  workflow_dispatch:

env:
  CONFIGURATION: Release
  
jobs:
  Build:
    runs-on: ubuntu-latest
    #runs-on: dotnet-scaleset
    #runs-on: self-hosted
    steps:
    - name: Check Linux version
      if: ${{ runner.os == 'Linux' }}
      run: lsb_release -a
      
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/MyFirstProject.sln
    
    - name: Build
      run: dotnet build src/MyFirstProject.sln --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test src/MyFirstProject.Tests/MyFirstProject.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --verbosity normal --logger "junit;LogFilePath=TestResults/tests.xml"
    
    #- name: Create test summary
    #  uses: test-summary/action@dist
    #  with:
    #    paths: src/MyFirstProject.Tests/TestResults/tests.xml
    #  if: success() || failure()

    #- name: Test Report
    #  uses: dorny/test-reporter@v1
    #  if: success() || failure()
    #  with:
    #    name: UnitTests
    #    path: src/MyFirstProject.Tests/TestResults/tests.xml
    #    reporter: java-junit
