name: dotnetcore-webapp-ci

on:
  push:
    branches: [ "features/*" ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CONFIGURATION: Release
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/MyFirstProject.sln
    
    - name: Build
      run: dotnet build src/MyFirstProject.sln --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test src/MyFirstProject.Tests/MyFirstProject.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --verbosity normal --logger "trx;LogFileName=test-results.trx"
       
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: UnitTests
        path: src/MyFirstProject.Tests/TestResults/*.trx
        reporter: dotnet-trx
        
    - name: Publish APP
      run: dotnet publish src/MyFirstProject.WebApp/MyFirstProject.WebApp.csproj --no-build --configuration ${{ env.CONFIGURATION }} --output PublishApp

    - name: Publish API
      run: dotnet publish src/MyFirstProject.WebApi/MyFirstProject.WebApi.csproj --no-build --configuration ${{ env.CONFIGURATION }} --output PublishApi

    - name: Upload APP Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-artifact
        path: PublishApp
    
    - name: Upload API Artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-artifact
        path: PublishApi
